### ISSUE TITLE
Font size on website

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/education.rstudio.com#82]
I think we should make the body font size a bit larger on the website. 16px is the minimum recommendation, though I think a size like [here](https://web.cvent.com/event/505ea09a-1342-4057-8a3a-64fcf331f23b/summary) seems better -- 19px. 

I believe the change would be in the following line:

https://github.com/rstudio/education.rstudio.com/blob/ce49094989c4d7d75706190c55ccec99f103a128/themes/hugo-tourmaline/static/css/main-site.css#L82

I didn't want to open a PR without discussion since this might affect quite a bit, but I do think a larger body size would be good. Currently, I find the pages hard to read and the size difference between headers and body text in blog posts seems huge.

**Comment by apreshill** [comment]
How about doing a PR and then we can see if all looks well in the deploy preview?

**Comment by apreshill** [comment]
(also note the CSS was built around tidyverse.org's original CSS, so if we fix with our site I'll do a PR to change the underlying Hugo theme to change it everywhere if too small- mainly I just want to see if this change blows up other things :)

Probably best to fix it here and not in the themes/ folder:
https://github.com/rstudio/education.rstudio.com/blob/ce49094989c4d7d75706190c55ccec99f103a128/static/css/edu.css#L1
